# Generated by Django 6.1 on 2026-08-28 20:10
# noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "correlation_id",
                    models.CharField(
                        db_index=True, help_text="UUID da requisição HTTP para rastreamento de fluxo.", max_length=64
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTH", "Autenticação OAuth2/JWT"),
                            ("IMPERSONATE", "Sessão Impersonada"),
                            ("API", "Acesso a API / Endpoint"),
                            ("SECURITY", "Alerta de Segurança"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Ex: auth.login.success, auth.jwt.issued, impersonate.start, api.ninja.access",
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informação"),
                            ("WARNING", "Aviso / Suspeito"),
                            ("CRITICAL", "Crítico / Falha de Segurança"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "application_name",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Nome da aplicação consumidor (ex: sas-painel)",
                        max_length=100,
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Username/Matrícula preservado para integridade auditável",
                        max_length=150,
                    ),
                ),
                ("impersonator_identifier", models.CharField(blank=True, db_index=True, default="", max_length=150)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        help_text="IP bruto original (acesso restrito por permissão)",
                        null=True,
                    ),
                ),
                (
                    "ip_hashed",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Hash SHA-256 do IP para dashboards e analytics sem PII",
                        max_length=64,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                ("request_path", models.CharField(blank=True, db_index=True, default="", max_length=500)),
                ("request_method", models.CharField(blank=True, default="", max_length=10)),
                ("status_code", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                (
                    "duration_ms",
                    models.FloatField(blank=True, help_text="Tempo de resposta em milissegundos", null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "impersonator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events_as_impersonator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Auditoria",
                "verbose_name_plural": "Eventos de Auditoria",
                "ordering": ["-timestamp"],
                "permissions": [("view_raw_ip", "Pode visualizar o IP bruto nos logs de auditoria")],
                "indexes": [
                    models.Index(fields=["timestamp", "category"], name="django_suap_timesta_b8fc6c_idx"),
                    models.Index(fields=["application_name", "timestamp"], name="django_suap_applica_57e3ea_idx"),
                    models.Index(fields=["user_identifier", "timestamp"], name="django_suap_user_id_9bf6a5_idx"),
                    models.Index(fields=["correlation_id"], name="django_suap_correla_fa7494_idx"),
                ],
            },
        ),
    ]
