# Generated by Django 6.1 on 2026-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="application_name",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Nome da aplicação consumidor (ex: sas-painel)",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="correlation_id",
            field=models.CharField(
                db_index=True, help_text="UUID da requisição HTTP para rastreamento de fluxo.", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                db_index=True,
                help_text="Ex: auth.login.success, auth.jwt.issued, impersonate.start, api.ninja.access",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="impersonator_identifier",
            field=models.CharField(blank=True, db_index=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="ip_hashed",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hash SHA-256 do IP para dashboards e analytics sem PII",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="request_method",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="request_path",
            field=models.CharField(blank=True, db_index=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="severity",
            field=models.CharField(
                choices=[
                    ("INFO", "Informação"),
                    ("WARNING", "Aviso / Suspeito"),
                    ("CRITICAL", "Crítico / Falha de Segurança"),
                ],
                db_index=True,
                default="INFO",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="user_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Username/Matrícula preservado para integridade auditável",
                max_length=256,
            ),
        ),
    ]
