# Generated by Django 6.1 on 2026-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_audit", "0002_alter_auditevent_application_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="request_path",
            field=models.CharField(blank=True, db_index=True, default="", max_length=500),
        ),
    ]
