# Generated by Django 6.1 on 2026-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dadosbrutos",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dadosbrutos",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="updated_at",
        ),
    ]
