# Generated by Django 6.1 on 2026-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_profile", "0002_remove_dadosbrutos_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="nome_registro",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
