# Generated by Django 6.1 on 2026-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_profile", "0003_perfil_nome_registro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="email_escolar",
        ),
        migrations.AddField(
            model_name="perfil",
            name="situacao_sistemica",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
