# Generated by Django 6.1 on 2026-08-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_profile", "0004_remove_perfil_email_escolar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="cota_mec",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="perfil",
            name="cota_sistec",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="perfil",
            name="linha_pesquisa",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="perfil",
            name="matricula_regular",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="turno",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
