# Generated by Django 6.1 on 2026-08-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_profile", "0006_alter_dadosbrutos_data_alter_perfil_campus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="first_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="primeiro login"),
        ),
        migrations.AddField(
            model_name="perfil",
            name="settings",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="configurações/preferências"),
        ),
    ]
