# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_user_from_perfil(apps, schema_editor):
    DadosBrutos = apps.get_model("django_suap_auth_profile", "DadosBrutos")
    Vinculo = apps.get_model("django_suap_auth_profile", "Vinculo")

    db_field_names = [f.name for f in DadosBrutos._meta.get_fields()]
    if "perfil" in db_field_names:
        for db in DadosBrutos.objects.filter(perfil__isnull=False):
            db.user_id = db.perfil.user_id
            db.save(update_fields=["user"])

    vinculo_field_names = [f.name for f in Vinculo._meta.get_fields()]
    if "perfil" in vinculo_field_names:
        for v in Vinculo.objects.filter(perfil__isnull=False):
            v.user_id = v.perfil.user_id
            v.save(update_fields=["user"])


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_suap_auth_profile", "0007_perfil_first_login_perfil_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosbrutos",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suap_raw_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vinculo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suap_vinculos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(populate_user_from_perfil, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="dadosbrutos",
            name="perfil",
        ),
        migrations.RemoveField(
            model_name="vinculo",
            name="perfil",
        ),
        migrations.AlterField(
            model_name="dadosbrutos",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suap_raw_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vinculo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suap_vinculos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
