# Generated by Django 6.1 on 2026-08-21 16:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSincronizacaoErro",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("endpoint", models.CharField(max_length=255, verbose_name="endpoint")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="status HTTP")),
                ("mensagem_erro", models.TextField(verbose_name="mensagem de erro")),
                (
                    "data_ocorrencia",
                    models.DateTimeField(blank=True, editable=False, verbose_name="data da ocorrência"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical erro de sincronização",
                "verbose_name_plural": "historical erros de sincronização",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SincronizacaoErro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.CharField(max_length=255, verbose_name="endpoint")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="status HTTP")),
                ("mensagem_erro", models.TextField(verbose_name="mensagem de erro")),
                ("data_ocorrencia", models.DateTimeField(auto_now_add=True, verbose_name="data da ocorrência")),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erros_sincronizacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "erro de sincronização",
                "verbose_name_plural": "erros de sincronização",
                "ordering": ["-data_ocorrencia"],
            },
        ),
    ]
