# Generated by Django 6.1 on 2026-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_suap_auth_erros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsincronizacaoerro",
            name="endpoint",
            field=models.CharField(max_length=256, verbose_name="endpoint"),
        ),
        migrations.AlterField(
            model_name="sincronizacaoerro",
            name="endpoint",
            field=models.CharField(max_length=256, verbose_name="endpoint"),
        ),
    ]
